version: "3.1"

services:
  scheduler-proxy:
    image: traefik:1.7 # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: duopassword
      POSTGRES_USER: duouser
      POSTGRES_DB: duo
    ports:
      - 5432:5432
    volumes:
      - "./${USER_OFFICE_BACKEND_DIR}/db_patches/:/docker-entrypoint-initdb.d/"

  factory:
    image: "ghcr.io/userofficeproject/user-office-factory:${USER_OFFICE_FACTORY_TAG}"
    init: true
    environment:
      NODE_ENV: development
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_USER: duouser
      DATABASE_PASSWORD: duopassword
      DATABASE_DATABASE: duo
    ports:
      - 4500:4500
    cap_add:
      - SYS_ADMIN

  dev-auth-server:
    image: "ghcr.io/userofficeproject/user-office-development-authorization-server:develop"
    environment:
      DATABASE_URL: postgres://duouser:duopassword@db:5432/duo
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - "db"

  backend:
    image: "ghcr.io/userofficeproject/user-office-backend:${USER_OFFICE_BACKEND_TAG}"
    environment:
      DATABASE_URL: postgres://duouser:duopassword@db:5432/duo
      secret: qMyLZALzs229ybdQXNyzYRdju7X784TH
      tokenLife: 7d
      baseURL: localhost:3000
      SPARKPOST_TOKEN: dummytoken
      NODE_ENV: development
      DEPENDENCY_CONFIG: e2e
      USER_OFFICE_FACTORY_ENDPOINT: ${USER_OFFICE_FACTORY_ENDPOINT}
      TZ: Europe/Stockholm
      DATE_FORMAT: dd-MM-yyyy
      DATE_TIME_FORMAT: dd-MM-yyyy HH:mm
      EMAIL_AS_EXTERNAL_TOKEN_AUTHORIZATION: "true"
      EAM_AUTH_URL: https://ios.esss.lu.se
      EAM_AUTH_SECRET: dummyEAMsecret
      EAM_AUTH_USER: dummyAuthUser
      EAM_AUTH_PASS: dummyAuthPass
      EAM_API_URL: https://ios.esss.lu.se:7443
      EAM_PART_CODE: 12413
      AUTH_DISCOVERY_URL: http://locahost:5000/.well-known/openid-configuration
      AUTH_CLIENT_ID: useroffice
      AUTH_CLIENT_SECRET: useroffice
    labels:
      - "traefik.frontend.rule=PathPrefix:/api, /downloads, /files, /download, /uploads"
      - "traefik.port=4000"
    volumes:
      - "./${USER_OFFICE_BACKEND_DIR}/db_patches:/home/node/app/db_patches"

  scheduler-frontend:
    image: "user-office-scheduler-frontend:${BUILD_TAG}"
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=80"
    depends_on:
      - gateway

  cypress:
    image: e2e-cypress:latest
    ipc: host # see https://github.com/cypress-io/cypress/issues/350
    entrypoint:
      ["/wait-for-frontend.sh", "scheduler-frontend:80", "npm run cy:run"]
    depends_on:
      - scheduler-frontend
    volumes:
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/screenshots:/tmp/screenshots"
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/fixtures:/e2e/cypress/fixtures"
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/integration:/e2e/cypress/integration"
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/plugins:/e2e/cypress/plugins"
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/support:/e2e/cypress/support"
