name: Generate SDK

on: [push]

jobs:
  generate-sdk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: develop

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: UserOfficeProject/user-office-core
        path: user-office-core
        ref: develop

    - name: Set up environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Start applications
      run: docker compose -f docker-compose.sdk.yml up -d

    - name: Wait for containers to be up
      run: |
        echo "Waiting for containers to be up..."
        while : ; do
          if [[ "$(docker compose -f docker-compose.sdk.yml ps --services --filter "status=running" | wc -l)" == "$(docker compose -f docker-compose.sdk.yml config --services | wc -l)" ]]; then
            echo "All containers are up!"
            docker ps
            break
          fi
          echo "Not all containers are up. Waiting..."
          sleep 10
        done

    - name: Wait for backend to start
      run: docker exec user-office-scheduler-gateway-1 sh -c 'until wget -qO- --server-response http://backend:4000/health 2>&1 | awk "/^  HTTP/{print \$2}" | grep -q 200; do echo "Waiting for 200 response..."; sleep 5; done'

    - name: Wait for scheduler-backend to start
      run: docker exec user-office-scheduler-gateway-1 sh -c 'until wget -qO- --server-response http://scheduler-backend:4200/health-check 2>&1 | awk "/^  HTTP/{print \$2}" | grep -q 200; do echo "Waiting for 200 response..."; sleep 5; done'

    - name: Install frontend dependencies
      working-directory: apps/frontend
      run: npm ci

    - name: Install backend dependencies
      working-directory: apps/backend
      run: npm ci

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
    
    - name: Generate SDK for frontend
      working-directory: apps/frontend
      env:
        SCHEMA_URL: http://0.0.0.0:4100/graphql
      run: npm run generate:local

    - name: Generate SDK for backend
      working-directory: apps/backend
      env:
        SCHEMA_URL: http://0.0.0.0:4100/graphql
      run: npm run generate:local

    - name: Remove user-office-core repo
      run: rm -rf user-office-core

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: develop
        title: 'chore(sdk): update generated sdk after core changes'
        body: 'Automatically generated SDK update'

    - name: Auto-merge if checks pass
      uses: pascalgn/automerge-action@v0.16.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "chore(sdk): update generated sdk after core changes"
